import { useTheme } from "@emotion/react";
import Button from "components/atoms/Button";
import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";

const Home: NextPage = () => {
  // const theme = useAppSelector((state) => state.theme);
  // const theme = useTheme();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Next.js</h1>
        <Button>Click Me</Button>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
